import {
  int,
  varchar,
  text,
  timestamp,
  mysqlTable,
  mysqlEnum,
  float,
  json,
  boolean,
  bigint,
} from "drizzle-orm/mysql-core";

/**
 * Core user table (Manus OAuth)
 */
export const users = mysqlTable("users", {
  id: int("id").autoincrement().primaryKey(),
  openId: varchar("openId", { length: 64 }).notNull().unique(),
  name: text("name"),
  email: varchar("email", { length: 320 }),
  loginMethod: varchar("loginMethod", { length: 64 }),
  role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(),
  // Artist profile fields
  artistName: varchar("artistName", { length: 100 }),
  bio: text("bio"),
  bandlabUrl: varchar("bandlabUrl", { length: 500 }),
  spotifyUrl: varchar("spotifyUrl", { length: 500 }),
  websiteUrl: varchar("websiteUrl", { length: 500 }),
  walletAddress: varchar("walletAddress", { length: 42 }),
  // Invitation system
  isVerified: boolean("isVerified").default(false).notNull(),
  invitedBy: int("invitedBy"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(),
});
export type User = typeof users.$inferSelect;
export type InsertUser = typeof users.$inferInsert;

/**
 * Invitation tokens — generated by verified users
 */
export const invitations = mysqlTable("invitations", {
  id: int("id").autoincrement().primaryKey(),
  token: varchar("token", { length: 64 }).notNull().unique(),
  createdBy: int("createdBy").notNull(),
  usedBy: int("usedBy"),
  usedAt: timestamp("usedAt"),
  expiresAt: timestamp("expiresAt"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});
export type Invitation = typeof invitations.$inferSelect;
export type InsertInvitation = typeof invitations.$inferInsert;

/**
 * Stems — core audio file with decentralized storage
 */
export const stems = mysqlTable("stems", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  fileName: varchar("fileName", { length: 255 }).notNull(),
  // Decentralized storage (IPFS/Filecoin via web3.storage)
  ipfsCid: varchar("ipfsCid", { length: 128 }),
  ipfsUrl: text("ipfsUrl"),
  stemUri: varchar("stemUri", { length: 200 }), // stem://CID
  // Fallback S3 (optional)
  s3Key: varchar("s3Key", { length: 512 }),
  s3Url: text("s3Url"),
  duration: float("duration"),
  fileSize: int("fileSize"),
  mimeType: varchar("mimeType", { length: 50 }),
  // NFT
  nftTokenId: varchar("nftTokenId", { length: 100 }),
  nftTxHash: varchar("nftTxHash", { length: 100 }),
  nftContractAddress: varchar("nftContractAddress", { length: 42 }),
  nftChain: varchar("nftChain", { length: 50 }).default("base-sepolia"),
  isMinted: boolean("isMinted").default(false).notNull(),
  // Moderation
  isFlagged: boolean("isFlagged").default(false).notNull(),
  flagReason: text("flagReason"),
  flaggedBy: int("flaggedBy"),
  flaggedAt: timestamp("flaggedAt"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});
export type Stem = typeof stems.$inferSelect;
export type InsertStem = typeof stems.$inferInsert;

/**
 * Stem metadata — audio analysis results
 */
export const stemMetadata = mysqlTable("stemMetadata", {
  id: int("id").autoincrement().primaryKey(),
  stemId: int("stemId").notNull().unique(),
  bpm: float("bpm"),
  key: varchar("key", { length: 20 }),
  instrumentType: varchar("instrumentType", { length: 100 }),
  genreTags: json("genreTags").$type<string[]>(),
  energyLevel: float("energyLevel"),
  mfccVector: json("mfccVector").$type<number[]>(),
  waveformData: json("waveformData").$type<number[]>(),
  analyzedAt: timestamp("analyzedAt").defaultNow().notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});
export type StemMetadata = typeof stemMetadata.$inferSelect;
export type InsertStemMetadata = typeof stemMetadata.$inferInsert;

/**
 * Ownership & licensing
 */
export const ownershipLicensing = mysqlTable("ownershipLicensing", {
  id: int("id").autoincrement().primaryKey(),
  stemId: int("stemId").notNull().unique(),
  creatorId: int("creatorId").notNull(),
  licenseType: mysqlEnum("licenseType", ["cc0", "cc-by", "cc-by-nc", "proprietary"]).default("cc-by").notNull(),
  royaltyPercentage: float("royaltyPercentage").default(0),
  usageRights: text("usageRights"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});
export type OwnershipLicensing = typeof ownershipLicensing.$inferSelect;

/**
 * Stem collections (playlists/projects)
 */
export const stemCollections = mysqlTable("stemCollections", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  name: varchar("name", { length: 100 }).notNull(),
  description: text("description"),
  isPublic: boolean("isPublic").default(false).notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});
export type StemCollection = typeof stemCollections.$inferSelect;

/**
 * Collection ↔ Stem many-to-many
 */
export const collectionStems = mysqlTable("collectionStems", {
  id: int("id").autoincrement().primaryKey(),
  collectionId: int("collectionId").notNull(),
  stemId: int("stemId").notNull(),
  order: int("order").default(0),
});

/**
 * Matching scores cache
 */
export const matchingScores = mysqlTable("matchingScores", {
  id: int("id").autoincrement().primaryKey(),
  stemId1: int("stemId1").notNull(),
  stemId2: int("stemId2").notNull(),
  totalScore: float("totalScore").notNull(),
  bpmScore: float("bpmScore"),
  keyScore: float("keyScore"),
  timbreScore: float("timbreScore"),
  genreScore: float("genreScore"),
  cachedAt: timestamp("cachedAt").defaultNow().notNull(),
});
export type MatchingScore = typeof matchingScores.$inferSelect;

/**
 * Match notifications — when two stems are compatible
 */
export const matchNotifications = mysqlTable("matchNotifications", {
  id: int("id").autoincrement().primaryKey(),
  toUserId: int("toUserId").notNull(),
  fromUserId: int("fromUserId").notNull(),
  stemId1: int("stemId1").notNull(),
  stemId2: int("stemId2").notNull(),
  score: float("score").notNull(),
  isRead: boolean("isRead").default(false).notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});
export type MatchNotification = typeof matchNotifications.$inferSelect;

/**
 * BandLab imported projects
 */
export const bandlabProjects = mysqlTable("bandlabProjects", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  projectUrl: text("projectUrl").notNull(),
  projectName: varchar("projectName", { length: 200 }),
  parsedData: json("parsedData"),
  importedAt: timestamp("importedAt").defaultNow().notNull(),
});
export type BandlabProject = typeof bandlabProjects.$inferSelect;

/**
 * Stem flags / copyright reports
 */
export const stemFlags = mysqlTable("stemFlags", {
  id: int("id").autoincrement().primaryKey(),
  stemId: int("stemId").notNull(),
  reportedBy: int("reportedBy").notNull(),
  reason: mysqlEnum("reason", ["copyright", "inappropriate", "spam", "other"]).notNull(),
  details: text("details"),
  status: mysqlEnum("status", ["pending", "reviewed", "dismissed"]).default("pending").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});
export type StemFlag = typeof stemFlags.$inferSelect;
